### ISSUE TITLE
Default initial value not working

### ISSUE THREAD

**Issue by JulioOrellana** [jundat95/switch-react-native#1]
Hello, I am using your Switch component and it works very smoothly and I like it. The issue is that the default value is not working as you can see in the images.

![screen shot 2017-08-31 at 3 07 59 pm](https://user-images.githubusercontent.com/10372340/29938243-854c0dd2-8e5e-11e7-9f7a-ad727d432ec9.png)
![screen shot 2017-08-31 at 3 08 22 pm](https://user-images.githubusercontent.com/10372340/29938245-86a7a812-8e5e-11e7-8076-cb3b7bface29.png)

I don't know if this is a bug or I am missing something.
Thanks for your component!

I am using 

RN 0.44.0
R   16.0.0-alpha.6
Switch RN 1.0.5

**Comment by gjundat95** [comment]
Thank you for your questions
To solve the above problem: 
- update version switch in package.json 
"switch-react-native": "^1.0.7"
- Edit source code
 <Switch
          width={widthScreen}
          activeText={'PDP'}
          inActiveText={'PRS'}
          activeTextStyle={{ fontSize: 14, fontWeight: 'bold', color: '#215e79' }}
          inActiveTextStyle={{ fontSize: 14, fontWeight: 'bold', color: '#ffffff' }}
          activeStyle={{ backgroundColor: '#ffffff' }}
          backgroundStyle={{ backgroundColor: '#215e79' }}
          onValueChange={(value) => this._onPressSwitch(value)}
        />
